name: quickpass_mobile
description: QuickPass Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.0
  flutter_animate: ^4.0.0
  google_fonts: ^6.0.0
  pin_code_fields: ^8.0.0
  device_info_plus: ^9.0.0
  mobile_scanner: ^5.0.0
  sqflite: ^2.3.0
  path: ^1.8.0
  encrypt: ^5.0.1
  flutter_vibrate: ^1.3.0
  uuid: ^4.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
