dependencies:
  json_annotation: ^4.8.0
  device_info_plus: ^9.0.0
  flutter_animate: ^4.0.0
  google_fonts: ^6.0.0
  pin_code_fields: ^8.0.0
dev_dependencies:
  json_serializable: ^6.7.0
  build_runner: ^2.4.0